import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import userRouter from "./user";
import questionsRouter from "./questions";
import examSessionRouter from "./examSession";
import paystackRouter from "./paystack";
import generateQuestionsRouter from "./generateQuestions";
import materialsRouter from "./materials";
import noticesRouter from "./notices";
import gamesRouter from "./games";
import studyPlanRouter from "./studyPlan";
import shareRouter from "./share";
import adminBalanceRouter from "./adminBalance";
import adminPasswordRouter from "./adminPassword";
import chatRouter from "./chat";
import clinicalCaseRouter from "./clinicalCase";
import dailyMcqRouter from "./dailyMcq";
import generateTheoryQuestionsRouter from "./generateTheoryQuestions";
import theoryExamScoreRouter from "./theoryExamScore";
import virtualAccountRouter from "./virtualAccount";
import studyNotesRouter from "./studyNotes";
import tokensRouter from "./tokens";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(paystackRouter);
router.use(userRouter);
router.use(questionsRouter);
router.use(examSessionRouter);
router.use(generateQuestionsRouter);
router.use(materialsRouter);
router.use(noticesRouter);
router.use(gamesRouter);
router.use(studyPlanRouter);
router.use(shareRouter);
router.use(adminBalanceRouter);
router.use(adminPasswordRouter);
router.use(chatRouter);
router.use(clinicalCaseRouter);
router.use(dailyMcqRouter);
router.use(generateTheoryQuestionsRouter);
router.use(theoryExamScoreRouter);
router.use(virtualAccountRouter);
router.use(studyNotesRouter);
router.use(tokensRouter);

export default router;
